spring:
  application:
    name: coffee-order-system
  profiles:
    default: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

data-platform:
  base-url: http://localhost:8089
  connect-timeout: 1s
  read-timeout: 3s
  retry:
    enabled: true
    fixed-delay: 60000
    max-count: 5
    batch-size: 100